---
# Create users

- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Add sudoers users to wheel group
  user: name=deployer groups=wheel append=yes state=present createhome=yes

- name: Create the deployer user
  user:
    name: deployer
    shell: /bin/bash
    groups: wheel
    append: yes

- name: Set authorized key for user deployer copying it from current user
  authorized_key:
    user: deployer
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/mongeese-footprints.pub') }}"
