- name: Install unzip
  apt: name=unzip state=present

- name: Download Vault
  get_url:
    url: "https://releases.hashicorp.com/vault/0.11.5/vault_0.11.5_linux_amd64.zip"
    dest: "/tmp/vault/vault_0.11.5_linux_amd64.zip"
    timeout: "30"

- name: Unarchive Vault and install binary
  unarchive:
    remote_src: true
    src: "/tmp/vault/vault_0.11.5_linux_amd64.zip"
    dest: "/usr/local/bin"
    owner: "ubuntu"
    mode: "0755"

- name: Cleanup
  file:
    path: "/tmp/vault"
    state: absent