---
- name: Elastic and Logstash
  hosts: elastic_and_logstash
  remote_user: ubuntu
  become: yes
  vars_files:
    - group_vars/geerlingguy_logstash/logstash.yml

  pre_tasks:
    - name: Create Logstash filter.
      copy:
        src: "13-footprints.conf"
        dest: "/etc/logstash/conf.d/13-footprints.conf"
        owner: root
        group: root
        mode: 0644
      notify: restart logstash

  roles:
    - geerlingguy.java
    - geerlingguy.logstash
    - geerlingguy.elasticsearch
    - geerlingguy.kibana