---
- name: Elastic and Logstash
  hosts: elastic_and_logstash
  remote_user: ubuntu
  become: yes
  vars_files:
    - group_vars/geerlingguy_logstash/logstash.yml

  roles:
    - geerlingguy.java
    - geerlingguy.logstash
    - geerlingguy.elasticsearch
    - geerlingguy.kibana