---
- name: Webservers
  hosts: webservers
  remote_user: ubuntu
  become: yes
  vars_files:
    - group_vars/geerlingguy_filebeat/filebeat.yml

  roles:
    - common
    - users
    - nginx
    - mysql
    - vim
    - geerlingguy.filebeat
    - {
        role: rvm.ruby,
        tags: ruby,
        become: yes,

        rvm1_rubies: ['ruby-2.1.5'],
        rvm1_install_flags: '--auto-dotfiles', # Remove --user-install from defaults
        rvm1_install_path: /usr/local/rvm,     # Set to system location
        rvm1_user: root                        # Need root account to access system location
    }

- name: Vault
  hosts: vault
  remote_user: ubuntu
  become: yes

  roles:
    - common
    - vault